export { toPercent, classifyMovement, MOVEMENT_THRESHOLD } from "./normalize";
export { flattenResults, matchPupils } from "./matchPupils";
export type { AssessmentResultEntry, MatchedPair, MatchResult } from "./matchPupils";
export { buildPupilMovements } from "./pupilMovement";
export { aggregateMovements, aggregateSchool } from "./aggregateMovement";
export { toDistribution, classifyPbdDirection, buildPbdSemesterMovements } from "./pbdSemesterMovement";
export type { PbdRecordInput } from "./pbdSemesterMovement";
export { classifyEvidence, buildCombinedEvidence } from "./combinedEvidence";
export { buildProgressModel } from "./buildProgressModel";
export type { ProgressInput } from "./buildProgressModel";
